### ISSUE TITLE
[feature request] Add formatting option

### ISSUE THREAD

**Issue by un-def** [luminousmen/xkblang#1]
It would be nice to have formatting options, something like this (from `xkblayout-state` help):

```
  %c -> current layout number
  %n -> current layout name
  %s -> current layout symbol
  %v -> current layout variant
  %e -> current layout variant (equals to %s if %v is empty)
  %C -> layout count
  %N -> layout names (one per line)
  %S -> layout symbols (one per line)
  %V -> layout variants (one per line)
  %E -> layout variants (one per line; layout symbol is used if variant is empty)
  %% -> A literal '%'
```

Usage:

```
$ xkblang
English (US)

$ xkblang 'layout: %n [%s]'
layout: English [us]

$ xkblang '%s\n%s\n#FFFFFF'
us
us
#FFFFFF
```

The latter example can be used as blocklet without any external wrapper — just add this string as `command` block property to your i3blocks config.

**Comment by luminousmen** [comment]
Thanks for you request! I added '-s' option for short version of output. I think it's the only appropriate format option in this project. If you need more formatting options use bash or awk.
